it works

diff --git a/services/docker-vacuum/Dockerfile b/services/docker-vacuum/Dockerfile
--- a/services/docker-vacuum/Dockerfile
+++ b/services/docker-vacuum/Dockerfile
@@ -13,7 +13,7 @@
 # if we touch the `package.json` file. Which doesn't happen so often.
 #
 
-FROM node:11.11 AS builder
+FROM node:11.11-alpine AS builder
 
 # NPM Install for building
 WORKDIR /usr/src/app-build
@@ -50,20 +50,7 @@ RUN npm run build
 # the idea is to keep this image as small as possible.
 #
 
-FROM node:11.11 AS runner
-
-# # Install GIT
-# RUN apk update && apk upgrade && \
-#     apk add --no-cache bash git openssh
-
-# # Let gyp modules
-# RUN apk add --no-cache --virtual .gyp \
-#         python \
-#         make \
-#         g++ \
-#     && npm install \
-#         [ your npm dependencies here ] \
-#     && apk del .gyp
+FROM node:11.11-alpine AS runner
 
 # Copy assets for build:
 WORKDIR /usr/src/app
@@ -76,6 +63,60 @@ ADD index.js /usr/src/app
 
 
 
+
+
+
+#
+# Install Docker to get the logs out of the shit
+# -- This is needed only for MacOSX pourpose --
+#
+
+RUN apk add --no-cache \
+		ca-certificates
+
+# set up nsswitch.conf for Go's "netgo" implementation (which Docker explicitly uses)
+# - https://github.com/docker/docker-ce/blob/v17.09.0-ce/components/engine/hack/make.sh#L149
+# - https://github.com/golang/go/blob/go1.9.1/src/net/conf.go#L194-L275
+# - docker run --rm debian:stretch grep '^hosts:' /etc/nsswitch.conf
+RUN [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' > /etc/nsswitch.conf
+
+ENV DOCKER_CHANNEL stable
+ENV DOCKER_VERSION 18.09.1
+# TODO ENV DOCKER_SHA256
+# https://github.com/docker/docker-ce/blob/5b073ee2cf564edee5adca05eee574142f7627bb/components/packaging/static/hash_files !!
+# (no SHA file artifacts on download.docker.com yet as of 2017-06-07 though)
+
+RUN set -eux; \
+	\
+# this "case" statement is generated via "update.sh"
+	apkArch="$(apk --print-arch)"; \
+	case "$apkArch" in \
+		x86_64) dockerArch='x86_64' ;; \
+		armhf) dockerArch='armel' ;; \
+		aarch64) dockerArch='aarch64' ;; \
+		ppc64le) dockerArch='ppc64le' ;; \
+		s390x) dockerArch='s390x' ;; \
+		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
+	esac; \
+	\
+	if ! wget -O docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${dockerArch}/docker-${DOCKER_VERSION}.tgz"; then \
+		echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
+		exit 1; \
+	fi; \
+	\
+	tar --extract \
+		--file docker.tgz \
+		--strip-components 1 \
+		--directory /usr/local/bin/ \
+	; \
+	rm docker.tgz; \
+	\
+	dockerd --version; \
+	docker --version
+
+
+
+
 #
 # Startup Info
 # ==========================================
@@ -84,6 +125,7 @@ ADD index.js /usr/src/app
 # Default environment configuration:
 ENV NODE_ENV development
 ENV LOG_LEVEL error
-ENV DATA_PATH /var/lib/gatsby-deploy
+ENV VACUUM_INTERVAL 600000
+ENV VACUUM_RULES "[{\"match\":\"(.*)\",\"retain\":2}]"
 
 ENTRYPOINT [ "node", "index.js" ]
